name: Create gh-pages repo

on:
  push:
    branches:
      - issue/7

jobs:
  first-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Create Files
        run: |
          mkdir ./public
          echo "## First github-pages" > ./public/index.hml
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
