name: Run tests every day

on:
  schedule:
    # 日本時間24時00分
    - cron: '0 15 * * *'

jobs:
  build:
    uses: kokoichi206/count-down-timer/.github/workflows/build.yml@2ff30e9e3cd45946ced2c3c1bf3dd238d7f5d1dd

  local-test:
    needs: [ build ]
    uses: kokoichi206/count-down-timer/.github/workflows/local-test.yml@2ff30e9e3cd45946ced2c3c1bf3dd238d7f5d1dd

  android-emulator-test:
    needs: [ build ]
    uses: kokoichi206/count-down-timer/.github/workflows/emulator-test.yml@2ff30e9e3cd45946ced2c3c1bf3dd238d7f5d1dd
